### PR TITLE
Add task displaying manifest before it gets deployed

### PR DESCRIPTION
**Pull request by lucaspinto**
This PR solves the issue #52  by adding a task for BOSH CLI v2 deployments that will display the manifest with all the operators and vars files included.

### CODE REVIEW

**Comment by o-orand** [comment]
@lucaspinto, it seems you introduce a new task. Is it possible to reuse https://github.com/orange-cloudfoundry/cf-ops-automation/tree/develop/concourse/tasks/bosh_interpolate instead ? Maybe it will require an additional task to display the generated manifest.

**Comment by lucaspinto** [comment]
I extend the task so that it actually displays the manifest as I thought I would mess with the task's output anyway. Are you fine with that?

**Comment by o-orand** [comment]
After a quick look, it seems you're trying to reintroduce the regression fixed by 1c14c5706c62c065c025d10551b643448ffdd41b

pipeline(depls): fixes bosh certificates after refactor regression
uses PipelineGenerator::BOSH_CERT_LOCATIONS[depls] instead of bosh_cert[depls]&.dump

**Comment by lucaspinto** [comment]
I thought I remembered a conversation where we say that we wanted to replace the use of the constants with the helpers we build. I will remove it.

**Comment by o-orand** [comment]
maybe :smile: , but in this case, we use the path of the file, not the content of the file, that why I don't think it's possible to use `bosh_cert[depls]&.dump`

**Comment by lucaspinto** [comment]
You're right. This should be gone by the next time the bell rings!

**Comment by o-orand** [comment]
closes #52

**Pull request merged**
